DROP DATABASE IF EXISTS SIME;
CREATE DATABASE BARBEARIA;
USE BARBEARIA;

DROP USER IF EXISTS 'barbearia'@'localhost';
CREATE USER 'barbearia'@'localhost' IDENTIFIED BY 'barbearia@1234';
GRANT SELECT, INSERT, UPDATE, DELETE ON BARBEARIA.* TO 'barbearia'@'localhost';

CREATE TABLE TIPO_USUARIO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    SENHA VARCHAR(255) NOT NULL,
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,   
    CLASSIFICACAO VARCHAR(25) DEFAULT "CLIENTE" 
);

CREATE TABLE BARBEIRO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(120) NOT NULL,
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE CLIENTE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,           
    EMAIL VARCHAR(100) NOT NULL UNIQUE,   
    TELEFONE VARCHAR(15)
);

CREATE TABLE AGENDAMENTO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_CLIENTE INT,
    ID_BARBEIRO INT,
    DATA_CORTE DATE,
    HORA_CORTE TIME,                      
    CONSTRAINT fk_cliente FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID),
    CONSTRAINT fk_barbeiro FOREIGN KEY (ID_BARBEIRO) REFERENCES BARBEIRO(ID)
);
