DROP DATABASE IF EXISTS SIME;
CREATE DATABASE BARBEARIA;
USE BARBEARIA;

DROP USER IF EXISTS 'barbearia'@'localhost';
CREATE USER 'barbearia'@'localhost' IDENTIFIED BY 'barbearia@1234';
GRANT SELECT, INSERT, UPDATE, DELETE ON BARBEARIA.* TO 'barbearia'@'localhost';


CREATE TABLE  TIPO_USUARIO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    SENHA VARCHAR(255) NOT NULL,
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP    
);

